version: '3.8'

services:
  cron-scheduler:
    build: .
    container_name: cron-tasks
    environment:
      # 定时任务配置 - 可通过.env文件覆盖
      - TASK1_SCHEDULE=${TASK1_SCHEDULE:-0 */2 * * *}    # 默认每2小时执行一次
      - TASK2_SCHEDULE=${TASK2_SCHEDULE:-*/30 * * * *}   # 默认每30分钟执行一次
      - TASK3_SCHEDULE=${TASK3_SCHEDULE:-0 9 * * 1}      # 默认每周一上午9点执行
      - TASK4_ENABLED=${TASK4_ENABLED:-true}             # 默认任务4启用
      - TIMEZONE=${TIMEZONE:-Asia/Shanghai}              # 时区设置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}                     # 日志级别
      - PYTHONUNBUFFERED=1
    volumes:
      # 数据持久化
      - ./data:/app/data
      # 日志文件挂载
      - ./logs:/app/logs
      # 如果需要编辑任务脚本，可以取消注释下面的行
      # - ./task1:/app/task1
      # - ./task2:/app/task2
      # - ./task3:/app/task3
    restart: unless-stopped
    # 健康检查配置
    healthcheck:
      test: ["CMD", "/app/scripts/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 网络配置（如果需要连接其他服务）
    # networks:
    #   - cron-network

# 如果需要自定义网络，取消注释
# networks:
#   cron-network:
#     driver: bridge

# 如果需要命名卷，取消注释
# volumes:
#   cron-data:
#   cron-logs: